### ISSUE TITLE
React support

### ISSUE THREAD

**Issue by nicobrinkkemper** [dreamonkey/responsive-image-loader#30]
I'm trying to get automatically resizing images to work with create-react-app. I'm using CRACO to mutate my webpack config. It's really hard to know for me what is going on as I can not directly see what the create-react-app default webpack config does. So far I've used responsive-loader (hasn't been maintained in a while) and this loader, none work out of the box with craco I believe. I believe there should be a straight forward way to do this.

Basically: 
- what config must be added to webpack to get images working in both CSS and TSX/TS/JSX/JS files?
- what caveats are there to look out for with create-react-app?
- how can development with create-react-app benefit from having automatically resizing images?

My previous experience from several years ago, my approach was to separate the image resizing step, having a intermediate build step where the html gets analysed by this plugin. This I want to prevent this time around by mutating the config of create-react-app to minimize the amount of build steps. Any help or previous experience on this topic is also greatly appreciated! Maybe if we can get a little discussion going about this, we can use the resulting information of that discussion as information for the docs.

Regards,

Nico

**Comment by IlCallo** [comment]
Hey @nicobrinkkemper
we have no experience about React or CRACO so I'm afraid I cannot help you more than the current [installation guide](https://github.com/dreamonkey/responsive-image-loader#-installation) does.

This loader works for HTML and CSS files, TSX/TS/JSX/JS files aren't supported because they're much more dynamic and difficult to parse and update correctly.

That said, you could try to create a new parser if you have the time and skills needed (we have few of the former and none of the latter). Currently the parsing step isn't configurable, but we could make it so.
